//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfull.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int id { get; set; }
        public int height { get; set; }
        public System.DateTime birthdate { get; set; }
        public int weight { get; set; }
        public int gender { get; set; }
    }
}
