//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfull.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageExercise
    {
        public int id { get; set; }
        public Nullable<int> pageId { get; set; }
        public Nullable<int> exerciseId { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual Page Page { get; set; }
    }
}
