//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTfull.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mHealthDatabaseEntities1 : DbContext
    {
        public mHealthDatabaseEntities1()
            : base("name=mHealthDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Diary> Diaries { get; set; }
        public virtual DbSet<Dizziness> Dizzinesses { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
    }
}
